spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/isg_db}
    username: ${SPRING_DATASOURCE_USERNAME:isg_user}
    password: ${SPRING_DATASOURCE_PASSWORD:isg_password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

application:
  security:
    jwt:
      # Sunucudaki JWT_SECRET ortam değişkenini okur, bulamazsa default olarak verdiğimiz Hex anahtarı kullanır.
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 900000
      refresh-token:
        expiration: 604800000